<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="WebApp" nsURI="WebApp" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="AplicacionWeb">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titulo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paginas" upperBound="-1"
        eType="#//PaginaWeb" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estilos" upperBound="-1"
        eType="#//EstiloVisual" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaginaWeb">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titulo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estilo" eType="#//EstiloVisual"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enlaces" upperBound="-1"
        eType="#//Enlace" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parrafos" upperBound="-1"
        eType="#//Parrafo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imagenes" upperBound="-1"
        eType="#//Imagen" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EstiloVisual">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parrafo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="texto" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enlace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destino" lowerBound="1"
        eType="#//PaginaWeb"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="texto" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Imagen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="texto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
